apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-vdag-metrics
  namespace: metrics-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: global-vdag-metrics
  template:
    metadata:
      labels:
        app: global-vdag-metrics
    spec:
      containers:
        - name: global-vdag-metrics
          image: 34.58.1.86:31280/metrics/global-vdags:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8890
          env:
            - name: REDIS_HOST
              value: "metrics-redis.metrics-system.svc.cluster.local"
            - name: MONGO_URL
              value: "mongodb://metrics-db-0.metrics-system.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: global-vdag-metrics
  namespace: metrics-system
spec:
  selector:
    app: global-vdag-metrics
  ports:
    - protocol: TCP
      port: 8890
      targetPort: 8890
      nodePort: 30203
  type: NodePort
