apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-redis
  namespace: metrics-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-redis
  template:
    metadata:
      labels:
        app: metrics-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-redis
  namespace: metrics-system
spec:
  selector:
    app: metrics-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30200
  type: NodePort
