{
 "title": "JanusGraph Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "JanusGraph Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1,java_lang_Runtime_Uptime{service=\"janusgraph-service\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JanusGraph Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(java_lang_Memory_HeapMemoryUsage_used{service=\"janusgraph-service\"})*100/sum(java_lang_Memory_HeapMemoryUsage_max{service=\"janusgraph-service\"})"
    }
   ]
  },
  {
   "title": "JanusGraph  CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{service=\"janusgraph-service\"}",
     "legendFormat": "System CPU Load - {{pod}}"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{service=\"janusgraph-service\"}",
     "legendFormat": "Process CPU Load - {{pod}}"
    }
   ]
  },
  {
   "title": "JanusGraph Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_FifteenMinuteRate{service=\"janusgraph-service\"})",
     "legendFormat": "15min_rate"
    },
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_FiveMinuteRate{service=\"janusgraph-service\"})",
     "legendFormat": "5min_rate"
    },
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_OneMinuteRate{service=\"janusgraph-service\"})",
     "legendFormat": "1min_rate"
    },
    {
     "expr": "JanusGraph_Cluster_metrics_requests_MeanRate{service=\"janusgraph-service\"}",
     "legendFormat": "mean_rate"
    }
   ]
  },
  {
   "title": "JanusGraph Requests MeanRate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "JanusGraph_Cluster_metrics_requests_MeanRate{service=\"janusgraph-service\"}",
     "legendFormat": "requests_mean_rate"
    }
   ]
  },
  {
   "title": "JanusGraph Cluster Requests",
   "type": "graph",
   "description": "JanusGraph_Cluster_metrics_requests_95thPercentile",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_75thPercentile{service=\"janusgraph-service\"})",
     "legendFormat": "requests_75%"
    },
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_95thPercentile{service=\"janusgraph-service\"})",
     "legendFormat": "requests_95%"
    },
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_99thPercentile{service=\"janusgraph-service\"})",
     "legendFormat": "requests_99%"
    },
    {
     "expr": "avg(JanusGraph_Cluster_metrics_requests_999thPercentile{service=\"janusgraph-service\"})",
     "legendFormat": "requests_99.9%"
    }
   ]
  },
  {
   "title": "JanusGraph Requests Count/second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(JanusGraph_Cluster_metrics_requests_Count{service=\"janusgraph-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JanusGraph Cluster Open Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(JanusGraph_Cluster_metrics_open_connections_Value{service=\"janusgraph-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JanusGraph Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(JanusGraph_Cluster_metrics_inflight_requests_Value{service=\"janusgraph-service\"})",
     "legendFormat": "inflight_requests"
    }
   ]
  },
  {
   "title": "Gremlin Server Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_errors_FifteenMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "15min_rate - {{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_errors_FiveMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "5min_rate - {{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_errors_MeanRate{service=\"janusgraph-service\"}",
     "legendFormat": "mean_rate - {{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_errors_OneMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "1min_rate - {{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Op Traversal Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_FifteenMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "15min_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_FiveMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "5min_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_OneMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "1min_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_MeanRate{service=\"janusgraph-service\"}",
     "legendFormat": "mean_{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Op Traversal Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_50thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "50_perc_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_75thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "75_perc_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_95thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "95_perc_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_traversal_95thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "99_perc_{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Op Eval Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_50thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "50_perc_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_75thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "75_perc_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_95thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "95_perc_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_99thPercentile{service=\"janusgraph-service\"}",
     "legendFormat": "99_perc_{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Op Eval Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_Count{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Op Eval Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_FifteenMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "15min_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_FiveMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "5min_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_OneMinuteRate{service=\"janusgraph-service\"}",
     "legendFormat": "1min_{{pod}}"
    },
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_op_eval_MeanRate{service=\"janusgraph-service\"}",
     "legendFormat": "mean_{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Cache Hit Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_gremlin_groovy_sessionless_class_cache_hit_count_Value{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Cache Miss Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_gremlin_groovy_sessionless_class_cache_miss_count_Value{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Cache Miss Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_gremlin_groovy_sessionless_class_cache_miss_rate_Value{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gremlin Server Error Count",
   "type": "graph",
   "description": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_errors_Count",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_errors_Count{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GremlinServer Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_gremlin_groovy_sessionless_class_cache_hit_rate_Value{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "GremlinServer Cache Eviction Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_org_apache_tinkerpop_gremlin_server_GremlinServer_gremlin_groovy_sessionless_class_cache_eviction_count_Value{service=\"janusgraph-service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JanusGraph Client Timeouts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(JanusGraph_Cluster_metrics_client_timeouts_Count{service=\"janusgraph-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JanusGraph Executor Queue Depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(JanusGraph_Cluster_metrics_executor_queue_depth_Value{service=\"janusgraph-service\"})",
     "legendFormat": "executor_queue_depth"
    }
   ]
  },
  {
   "title": "JanusGraph Connection Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(JanusGraph_Cluster_metrics_connection_errors_Count{service=\"janusgraph-service\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}