apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: framedb-2-storage-adhoc-bkp
  namespace: framedb-
spec:
  backupType: full
  br:
    cluster: framedb-2-storage
    clusterNamespace: framedb-storage-cluster
  from:
    host: "framedb-2-storage-tidb.framedb-storage-cluster.svc.cluster.local"
    port: 4000
    user: "admin"
    secretName: storage-cluster-backup-auth
  s3:
    provider: ceph
    secretName: backup-secret
    endpoint: rook-ceph-rgw-framedb-objectstore.rook-ceph.svc.cluster.local
    prefix: framedb-buckets
    bucket: framedb-buckets
  storageClassName: local-storage
  storageSize: "3Gi"