apiVersion: apps/v1
kind: Deployment
metadata:
  name: failure-notifier
  namespace: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failure-notifier
  template:
    metadata:
      labels:
        app: failure-notifier
    spec:
      containers:
        - name: failure-notifier
          image: 34.58.1.86:31280/mgmt/failure-notifier:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: POLICY_SYSTEM_EXECUTOR_ID
              value: "executor-001"
            - name: POLICY_EXECUTOR_HOST_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"
            - name: POLICY_DB_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"
---
apiVersion: v1
kind: Service
metadata:
  name: failure-notifier
  namespace: utils
spec:
  selector:
    app: failure-notifier
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
