apiVersion: apps/v1
kind: Deployment
metadata:
  name: failure-notifier
  namespace: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failure-notifier
  template:
    metadata:
      labels:
        app: failure-notifier
    spec:
      containers:
        - name: failure-notifier
          image: aiosv1/failure-notifier:v1
          ports:
            - containerPort: 5000
          env:
            - name: POLICY_EXECUTOR_API_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"  
            - name: POLICY_DB_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"
---
apiVersion: v1
kind: Service
metadata:
  name: failure-notifier
  namespace: utils
spec:
  selector:
    app: failure-notifier
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
