apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-server
  namespace: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-server
  template:
    metadata:
      labels:
        app: search-server
    spec:
      containers:
        - name: search-server
          image: 34.58.1.86:31280/mgmt/search-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 12000
          env:
            - name: POLICY_DB_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"
            - name: BLOCKS_SERVICE_URL
              value: "http://blocks-db-svc.registries.svc.cluster.local:3001"
            - name: VDAG_SERVICE_URL
              value: "http://vdag-db-svc.registries.svc.cluster.local:10501"
            - name: GLOBAL_CLUSTER_METRICS_URL
              value: "http://global-cluster-metrics.metrics-system.svc.cluster.local:8888"
            - name: VDAG_METRICS_SERVER_URL
              value: "http://global-vdag-metrics.metrics-system.svc.cluster.local:8890"
            - name: POLICY_EXECUTION_MODE
              value: "remote"
            - name: GLOBAL_BLOCK_METRICS_URL
              value: "http://global-block-metrics.metrics-system.svc.cluster.local:8889"
            - name: CLUSTER_SERVICE_URL
              value: "http://clusters-db-service.registries.svc.cluster.local:3000"
            - name: POLICIES_SERVER_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"
            - name: vDAG_TEMPLATE_STORE_API_URL
              value: "http://templates-registry-svc.registries.svc.cluster.local:9000"
            - name: POLICY_SYSTEM_EXECUTOR_ID
              value: "executor-001"
            - name: POLICY_EXECUTOR_HOST_URL
              value: "http://policies-system.registries.svc.cluster.local:10000"
            - name: CLUSTER_ID
              value: ""
            - name: COMPONENT_REGISTRY_API
              value: "http://components-registry-svc.registries.svc.cluster.local:4000"
            - name: SEARCH_SERVER_API_URL
              value: "http://search-server.utils.svc.cluster.local:12000"

---

apiVersion: v1
kind: Service
metadata:
  name: search-server
  namespace: utils
spec:
  selector:
    app: search-server
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
      nodePort: 30150
  type: NodePort
