apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-config
  namespace: framedb-config
  labels:
    app: cluster-config
spec:
  selector:
    matchLabels:
      app: cluster-config
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-config
    spec:
      containers:
      - name: cluster-config
        image: cluster-config:latest
        imagePullPolicy : Never
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
         - name : "DB_NAME"
           value : "framedb"
         - name : "MONGO_URI"
           value : "mongodb://admin:Friends123#@framedb-config-db-mongodb.framedb-config.svc.cluster.local:27017"
         - name : "LOGGING"
           value : "Yes"
        volumeMounts:
         - name : logging 
           mountPath : /logs
         - name : kubeconfig
           mountPath : /root/.kube
      volumes :
        - name : logging
          hostPath:
            path: /home/ubuntu/disk2
        - name : kubeconfig
          hostPath :
            path : /home/ubuntu/.kube

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-config-svc
  namespace: framedb-config
spec:
  selector:
    app: cluster-config
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort : 32502
  type: NodePort