apiVersion: v1
kind: Namespace
metadata:
  name: controllers
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-proxy
  namespace: controllers
spec:
  type: NodePort
  selector:
    app: grpc-proxy
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-proxy
  namespace: controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-proxy
  template:
    metadata:
      labels:
        app: grpc-proxy
    spec:
      containers:
        - name: proxy
          image: 34.58.1.86:31280/cluster/rpc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
