apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ""
  namespace : framedb-storage

  labels:
   jobType: "framedb-ingestion-schedule"
   jobNode: ""

spec:
  schedule: ""
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "test"
            image: ingestion-worker:latest
            command: ["env"]
          restartPolicy: OnFailure
#          nodeSelector:
#            framedb: ""