apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: framedb-monitoring
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.1.3
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        env:
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "Cog#2019"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-kubernetes-app,redis-datasource"
      volumes:
      - name: grafana-storage
        emptyDir: {}
      nodeSelector:
        primary: "True"