apiVersion: v1
kind: Service
metadata:
  name: grafana-gateway-service
  namespace: framedb-monitoring
spec:
  selector:
    app: grafana
  ports:
    - nodePort: 32000
      protocol: TCP
      port: 300
      targetPort: 3000
  type: NodePort