apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: framedb-backup-objects
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: framedb-objectstore
  objectStoreNamespace: rook-ceph
  region: us-east-1