// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: service/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceProxy_Infer_FullMethodName = "/InferenceProxy/infer"
)

// InferenceProxyClient is the client API for InferenceProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceProxyClient interface {
	Infer(ctx context.Context, in *InferenceMessage, opts ...grpc.CallOption) (*InferenceRespose, error)
}

type inferenceProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceProxyClient(cc grpc.ClientConnInterface) InferenceProxyClient {
	return &inferenceProxyClient{cc}
}

func (c *inferenceProxyClient) Infer(ctx context.Context, in *InferenceMessage, opts ...grpc.CallOption) (*InferenceRespose, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceRespose)
	err := c.cc.Invoke(ctx, InferenceProxy_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceProxyServer is the server API for InferenceProxy service.
// All implementations must embed UnimplementedInferenceProxyServer
// for forward compatibility.
type InferenceProxyServer interface {
	Infer(context.Context, *InferenceMessage) (*InferenceRespose, error)
	mustEmbedUnimplementedInferenceProxyServer()
}

// UnimplementedInferenceProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceProxyServer struct{}

func (UnimplementedInferenceProxyServer) Infer(context.Context, *InferenceMessage) (*InferenceRespose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedInferenceProxyServer) mustEmbedUnimplementedInferenceProxyServer() {}
func (UnimplementedInferenceProxyServer) testEmbeddedByValue()                        {}

// UnsafeInferenceProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceProxyServer will
// result in compilation errors.
type UnsafeInferenceProxyServer interface {
	mustEmbedUnimplementedInferenceProxyServer()
}

func RegisterInferenceProxyServer(s grpc.ServiceRegistrar, srv InferenceProxyServer) {
	// If the following call pancis, it indicates UnimplementedInferenceProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceProxy_ServiceDesc, srv)
}

func _InferenceProxy_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceProxyServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceProxy_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceProxyServer).Infer(ctx, req.(*InferenceMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceProxy_ServiceDesc is the grpc.ServiceDesc for InferenceProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InferenceProxy",
	HandlerType: (*InferenceProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "infer",
			Handler:    _InferenceProxy_Infer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/service.proto",
}
