// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: service/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferenceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcData       []byte                 `protobuf:"bytes,1,opt,name=rpc_data,json=rpcData,proto3" json:"rpc_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceMessage) Reset() {
	*x = InferenceMessage{}
	mi := &file_service_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceMessage) ProtoMessage() {}

func (x *InferenceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceMessage.ProtoReflect.Descriptor instead.
func (*InferenceMessage) Descriptor() ([]byte, []int) {
	return file_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceMessage) GetRpcData() []byte {
	if x != nil {
		return x.RpcData
	}
	return nil
}

type InferenceRespose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       bool                   `protobuf:"varint,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRespose) Reset() {
	*x = InferenceRespose{}
	mi := &file_service_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRespose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRespose) ProtoMessage() {}

func (x *InferenceRespose) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRespose.ProtoReflect.Descriptor instead.
func (*InferenceRespose) Descriptor() ([]byte, []int) {
	return file_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceRespose) GetMessage() bool {
	if x != nil {
		return x.Message
	}
	return false
}

var File_service_service_proto protoreflect.FileDescriptor

const file_service_service_proto_rawDesc = "" +
	"\n" +
	"\x15service/service.proto\"-\n" +
	"\x10InferenceMessage\x12\x19\n" +
	"\brpc_data\x18\x01 \x01(\fR\arpcData\",\n" +
	"\x10InferenceRespose\x12\x18\n" +
	"\amessage\x18\x01 \x01(\bR\amessage2?\n" +
	"\x0eInferenceProxy\x12-\n" +
	"\x05infer\x12\x11.InferenceMessage\x1a\x11.InferenceResposeB\x1bZ\x19rpc-proxy/service;serviceb\x06proto3"

var (
	file_service_service_proto_rawDescOnce sync.Once
	file_service_service_proto_rawDescData []byte
)

func file_service_service_proto_rawDescGZIP() []byte {
	file_service_service_proto_rawDescOnce.Do(func() {
		file_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_service_proto_rawDesc), len(file_service_service_proto_rawDesc)))
	})
	return file_service_service_proto_rawDescData
}

var file_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_service_proto_goTypes = []any{
	(*InferenceMessage)(nil), // 0: InferenceMessage
	(*InferenceRespose)(nil), // 1: InferenceRespose
}
var file_service_service_proto_depIdxs = []int32{
	0, // 0: InferenceProxy.infer:input_type -> InferenceMessage
	1, // 1: InferenceProxy.infer:output_type -> InferenceRespose
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_service_proto_init() }
func file_service_service_proto_init() {
	if File_service_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_service_proto_rawDesc), len(file_service_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_service_proto_goTypes,
		DependencyIndexes: file_service_service_proto_depIdxs,
		MessageInfos:      file_service_service_proto_msgTypes,
	}.Build()
	File_service_service_proto = out.File
	file_service_service_proto_goTypes = nil
	file_service_service_proto_depIdxs = nil
}
