apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhoc-serviers-registry
  namespace: registries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adhoc-serviers-registry
  template:
    metadata:
      labels:
        app: adhoc-serviers-registry
    spec:
      containers:
        - name: adhoc-serviers-registry
          image: aiosv1/adhoc-serviers-registry:v1
          ports:
            - containerPort: 6000
          env:
            - name: MONGO_URL
              value: "mongodb://registry-0.registries.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: adhoc-serviers-registry-svc
  namespace: registries
spec:
  selector:
    app: adhoc-serviers-registry
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 30105
  type: NodePort
