apiVersion: apps/v1
kind: Deployment
metadata:
  name: policies-system
  namespace: registries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policies-system
  template:
    metadata:
      labels:
        app: policies-system
    spec:
      containers:
        - name: policies-system
          image: 34.58.1.86:31280/policies/system:latest
          ports:
            - containerPort: 10000
          env:
            - name: RESOURCE_ALLOCATOR_API_URL
              value: "http://resource-allocator.services.svc.cluster.local:3000"
            - name: DB_URL
              value: "mongodb://registry-0.registries.svc.cluster.local:27017/policies"
            - name: POLICY_DB_URL
              value: "http://34.58.1.86:30102"
            - name: PUBLIC_DB_URL
              value: "mongodb://registry-0.registries.svc.cluster.local:27017/policies"
            - name: EXECUTOR_CONTAINER_IMAGE_NAME
              value: "34.58.1.86:31280/policies/executor:latest"
            - name: DEFAULT_POLICY_CONTAINER_IMAGE
              value: "34.58.1.86:31280/policies/functions-server:latest"
            - name: DEFAULT_POLICY_JOB_CONTAINER_IMAGE_NAME
              value: "34.58.1.86:31280/policies/jobs-runner:latest"
            - name: DB_API_URL
              value: "http://34.58.1.86:30102"
    
---

apiVersion: v1
kind: Service
metadata:
  name: policies-system
  namespace: registries
  labels:
    app: policies-system
spec:
  selector:
    app: policies-system
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 30102
  type: NodePort
