apiVersion: apps/v1
kind: Deployment
metadata:
  name: spec-registry
  namespace: registries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spec-registry
  template:
    metadata:
      labels:
        app: spec-registry
    spec:
      containers:
        - name: spec-registry
          image: aiosv1/spec-registry:v1
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://registry-0.registries.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: spec-registry-svc
  namespace: registries
spec:
  selector:
    app: spec-registry
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30107
  type: NodePort
