apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-db
  namespace: registries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-db
  template:
    metadata:
      labels:
        app: tasks-db
    spec:
      containers:
        - name: tasks-db
          image: aiosv1/tasks-db:v1
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://registry-0.registries.svc.cluster.local:27017"
        - name: status-writer
          image: aiosv1/status-writer:v1
          env:
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: tasks-db-svc
  namespace: registries
spec:
  selector:
    app: tasks-db
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30108
  type: NodePort
