apiVersion: apps/v1
kind: Deployment
metadata:
  name: templates-registry
  namespace: registries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templates-registry
  template:
    metadata:
      labels:
        app: templates-registry
    spec:
      containers:
        - name: templates-registry
          imagePullPolicy: Always
          image: 34.58.1.86:31280/registries/template-store:latest
          ports:
            - containerPort: 9000
          env:
            - name: MONGO_URL
              value: "mongodb://registry-0.registries.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: templates-registry-svc
  namespace: registries
spec:
  selector:
    app: templates-registry
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30106
  type: NodePort
