apiVersion: pingcap.com/v1alpha1
kind: BackupSchedule
metadata:
  name: ""
  namespace: framedb-storage-cluster
spec:
  maxReservedTime: "3h"
  schedule: ""
  backupTemplate:
    backupType: full
    br:
      cluster: ""
      clusterNamespace: framedb-storage-cluster
    from:
      host: ""
      port: 4000
      user: root
      secretName: tidb-secret
    s3:
      provider: s3
      secretName: backup-secret
      endpoint: ""
      prefix: ""
      bucket: ""